### ISSUE TITLE
显示ModuleNotFoundError: No module named 'nonebot_plugin_moegoe'

### ISSUE THREAD

**Issue by SANgaojie** [Yiyuiii/nonebot-plugin-moegoe#19]
请问怎么解决
![image](https://user-images.githubusercontent.com/120659771/207891225-b7b355c2-e803-45f1-b8f9-d4e7344045ab.png)
12-15 22:49:17 [ERROR] nonebot | Failed to import "nonebot_plugin_moegoe"
Traceback (most recent call last):
  File "c:\users\26314\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\26314\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\26314\AppData\Local\Programs\Python\Python38\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "c:\users\26314\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "c:\users\26314\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "c:\users\26314\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "c:\users\26314\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\users\26314\appdata\local\programs\python\python38\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "c:\users\26314\appdata\local\programs\python\python38\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "c:\users\26314\appdata\local\programs\python\python38\lib\site-packages\nb_cli\handlers\deploy.py", line 20, in run_bot
    module = importlib.import_module(module_name)
  File "c:\users\26314\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "D:\bot\nb2\.\bot.py", line 25, in <module>
    nonebot.load_plugin('nonebot_plugin_moegoe')
  File "c:\users\26314\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\load.py", line 34, in load_plugin
    return manager.load_plugin(module_path)
> File "c:\users\26314\appdata\local\programs\python\python38\lib\site-packages\nonebot\plugin\manager.py", line 141, in
 load_plugin
    module = importlib.import_module(name)
  File "c:\users\26314\appdata\local\programs\python\python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'nonebot_plugin_moegoe'

**Comment by Yiyuiii** [comment]
请确认你在这个python版本中安装了nonebot_plugin_moegoe
如果安装了，可以在这个路径中找到：“c:\users\26314\appdata\local\programs\python\python38\lib\site-packages”

**Comment by WindraiteLesd** [comment]
> 请确认你在这个python版本中安装了nonebot_plugin_moegoe 如果安装了，可以在这个路径中找到：“c:\users\26314\appdata\local\programs\python\python38\lib\site-packages”

如果使用nb的安装方法，bot目录里的pyproject上是这个名称：nonebot_plugin_moegoe，所以插件tool.poetry的包名是不是写的有问题？

**Comment by Yiyuiii** [comment]
> > 请确认你在这个python版本中安装了nonebot_plugin_moegoe 如果安装了，可以在这个路径中找到：“c:\users\26314\appdata\local\programs\python\python38\lib\site-packages”
> 
> 如果使用nb的安装方法，bot目录里的pyproject上是这个名称：nonebot_plugin_moegoe，所以插件tool.poetry的包名是不是写的有问题？

我不知道你说的逻辑是什么，请确认你在这个路径中能找到nonebot_plugin_moegoe：“c:\users\26314\appdata\local\programs\python\python38\lib\site-packages”

如果找不到，说明python调用有问题

**Comment by WindraiteLesd** [comment]
> > > 请确认你在这个python版本中安装了nonebot_plugin_moegoe 如果安装了，可以在这个路径中找到：“c:\users\26314\appdata\local\programs\python\python38\lib\site-packages”
> > 
> > 
> > 如果使用nb的安装方法，bot目录里的pyproject上是这个名称：nonebot_plugin_moegoe，所以插件tool.poetry的包名是不是写的有问题？
> 
> 我不知道你说的逻辑是什么，请确认你在这个路径中能找到nonebot_plugin_moegoe：“c:\users\26314\appdata\local\programs\python\python38\lib\site-packages”
> 
> 如果找不到，说明python调用有问题

以前版本安装是正常的，现在输入nb plugin install nonebot_plugin_moegoe或pip install nonebot_plugin_moegoe安装这个插件，pip输出中显示requirement already satisfied:nonebot-plugin-moegoe in xxx/lib/site-packages，但在site-packages里面只能找到一个dist文件夹，既没有"nonebot-plugin-moegoe"也没有"nonebot_plugin_moegoe"，我安装其它的插件是没有这样的问题的

**Comment by Yiyuiii** [comment]
好的我测试一下这个问题

**Comment by Yiyuiii** [comment]
确实是[pyproject.toml](https://github.com/Yiyuiii/nonebot-plugin-moegoe/blob/master/pyproject.toml)有问题，我修复这个问题以后重新上传了安装包，等一会以后可以下载
