### ISSUE TITLE
大佬这个一运行就报错咋办啊

### ISSUE THREAD

**Issue by PROBEFISH** [Yiyuiii/nonebot-plugin-moegoe#2]
08-21 20:05:54 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_moegoe, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "c:\Users\Administrator\Desktop\bot\probe\bot.py", line 57, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 634, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 601, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1905, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_moegoe\__init__.py", line 65, in _
    await cn_cmd.finish(cn_func(msg=msg, name=name))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 468, in finish
    await cls.send(message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 453, in send
    return await bot.send(event=event, message=_message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\adapter\bot.py", line 117, in call_api
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 131, in _call_api
    return handle_api_result(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\onebot\utils.py", line 47, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.exception.ActionFailed: <ActionFailed data=None, echo=3, msg=SEND_MSG_API_ERROR, retcode=100, status=failed, wording=请参考 go-cqhttp 端输出>

**Comment by Yiyuiii** [comment]
这个是api返回语音失败。
我刚测试api是正常的，最有可能的原因是api对输入要求很严，只支持有语义的*中文*和几个标点符号，输入如果包含无法转换的字符就会无法生成语音，英文，叠词等就大概率不行

**Comment by PROBEFISH** [comment]
我试了下单个字还有词都不行，还是我输入的方式有问题吗
08-21 20:29:05 [SUCCESS] nonebot | ONEBOT V11 3300918022 | [message.private.friend]: Message 775456497 from 1211181413 "让派蒙说中文：你好"
08-21 20:29:05 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_moegoe, type=message, priority=5, temp=False>
08-21 20:29:05 [WARNING] nonebot_plugin_gocqhttp | [3300918022] 转换CQ码 ({"type": "record", "data": {"file": "http://233366.proxy.nscc-gz.cn:8888?speaker=\u6d3e\u8499&text=\u4f60\u597d", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in %PATH% 将忽略本段CQ码.
08-21 20:29:05 [WARNING] nonebot_plugin_gocqhttp | [3300918022] 好友消息发送失败: 消息为空.
08-21 20:29:05 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_moegoe, type=message, priority=5, temp=False> running complete

**Comment by Yiyuiii** [comment]
看起来是少了一个依赖库ffmpeg，我检查一下然后给你反馈

**Comment by Yiyuiii** [comment]
这里的中文被不正当地转义了\u4f60，我测试一下它的原因

**Comment by Yiyuiii** [comment]
我测试了一下，`encode silk failed: convert pcm file error: exec: "ffmpeg": executable file not found in %PATH% `这个错误表示你的系统里没有ffmpeg，所以没有办法把获取的音频编码。
目前我正在寻找一种合适的解决方案

**Comment by Yiyuiii** [comment]
在nb群里问了一下，gocq依赖ffmpeg对音视频编解码，所以你需要在系统里安装ffmpeg来支持这个功能。

**Comment by xiayingLIULI** [comment]
大佬可以用langid来判断语种，这样就不会被转译了

**Comment by xiaorui158** [comment]
大佬可以用langid来判断语种，这样就不会被转译了

**Comment by Yiyuiii** [comment]
我后来测试对比了一下，这还不是转译的锅qwq

**Comment by PROBEFISH** [comment]
我试了下安装完重启下就能正常用了

**Comment by F1Justin** [comment]
> 

请问是pip安装ffmpeg吗? 重启是系统还是bot?

**Comment by Yiyuiii** [comment]
> > 
> 
> 请问是pip安装ffmpeg吗? 重启是系统还是bot?

ffmpeg是一个独立的软件，安装过程可自行搜索；保险起见需要重开命令行。

**Comment by F1Justin** [comment]
> 

用brew安装了ffmpeg, 没有重启任何东西就能运行了
