### ISSUE TITLE
日语和韩语没反应

### ISSUE THREAD

**Issue by QQzhuqiu** [Yiyuiii/nonebot-plugin-moegoe#4]
测试了一下插件，发现日语和韩语并无反应（包括日志），原神正常使用

**Comment by QQzhuqiu** [comment]
2022/8/22 下午3:44:53WARNING转换CQ码 ({"type": "record", "data": {"file": "https://moegoe.azurewebsites.net/api/speak?text=\u9593\u9055\u3063\u3066\u3044\u308b\u306e\u306f\u79c1\u3067\u306f\u306a\u304f\u3001\u3053\u306e\u4e16\u754c\u3067\u3059\u3002&id=0", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error:

**Comment by QQzhuqiu** [comment]
![QQ图片20220822154616](https://user-images.githubusercontent.com/111731744/185867680-ca801351-4330-47d5-abd7-0f186aaf848c.png)
![QQ图片20220822154621](https://user-images.githubusercontent.com/111731744/185867688-8106ea64-aa2f-4c6f-8b3c-7376df58bd43.png)

**Comment by QQzhuqiu** [comment]
没仔细看，有报错捏，ffmpeg有安装配置

**Comment by Yiyuiii** [comment]
你好，这个问题和 https://github.com/Yiyuiii/nonebot-plugin-moegoe/issues/3 一样，我中午将代码更新到0.3.0版本了，新代码应该可以正常使用

**Comment by QQzhuqiu** [comment]
08-22 16:02:28 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_russian, type=message, priority=5, temp=False> failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\Scripts\nb.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nb_cli\commands\main.py", line 30, in run
    run_bot(file, app)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nb_cli\handlers\deploy.py", line 25, in run_bot
    nonebot.run(app=f"{module_name}:{app}")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\main.py", line 575, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 629, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 596, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 1890, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_russian\__init__.py", line 194, in _
    await russian_manager.shot(bot, event, count)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_russian\data_source.py", line 384, in shot
    await self.end_game(bot, event)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot_plugin_russian\data_source.py", line 551, in end_game
    await bot.send(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 220, in send
    return await self.__class__.send_handler(self, event, message, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\onebot\v11\bot.py", line 175, in send
    return await bot.send_msg(**params)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\adapter\bot.py", line 117, in call_api
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\internal\adapter\bot.py", line 94, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 132, in _call_api
    return handle_api_result(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: <ActionFailed data=None, echo='32', msg='SEND_MSG_API_ERROR', retcode=100, status='failed', wording='请参考 go-cqhttp 端输出'>

**Comment by QQzhuqiu** [comment]
不过gocq没报之前那个“2022/8/22 下午3:44:53WARNING转换CQ码 ({"type": "record", "data": {"file": "[https://moegoe.azurewebsites.net/api/speak?text=\u9593\u9055\u3063\u3066\u3044\u308b\u306e\u306f\u79c1\u3067\u306f\u306a\u304f\u3001\u3053\u306e\u4e16\u754c\u3067\u3059\u3002&id=0](https://moegoe.azurewebsites.net/api/speak?text=%5Cu9593%5Cu9055%5Cu3063%5Cu3066%5Cu3044%5Cu308b%5Cu306e%5Cu306f%5Cu79c1%5Cu3067%5Cu306f%5Cu306a%5Cu304f%5Cu3001%5Cu3053%5Cu306e%5Cu4e16%5Cu754c%5Cu3067%5Cu3059%5Cu3002&id=0)", "magic": null, "cache": null, "proxy": null, "timeout": null}}) 到MiraiGo Element时出现错误: encode silk failed: convert pcm file error:”而是报了风控（不知道是不是那个消息的，但确实没出现之前那个报错

**Comment by Yiyuiii** [comment]
那啥，nonebot_plugin_russian是这个库的代码么

**Comment by Yiyuiii** [comment]
风控的话，可以检测一下bot能不能正常发其它的消息

**Comment by QQzhuqiu** [comment]
卧槽看错了抱歉，那就是没报错...但还是没有返回消息欸

**Comment by QQzhuqiu** [comment]
可以正常发送消息

**Comment by Yiyuiii** [comment]
> 卧槽看错了抱歉，那就是没报错...但还是没有返回消息欸

我怀疑是moegoe的插件优先级5比较低，被其它插件block掉了

**Comment by QQzhuqiu** [comment]
有返回了谢谢佬

**Comment by QQzhuqiu** [comment]
ok咱重新安装试试捏谢谢佬&nbsp;


皓月当空
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月22日(星期一) 下午3:53
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Yiyuiii/nonebot-plugin-moegoe] 日语和韩语没反应 (Issue #4)





 
你好，这个问题和 #3 一样，我中午将代码更新到0.3.0版本了，新代码应该可以正常使用
